// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuLjfqQRS662xKaPec_iFkRMXGNeY-Ma8',
    appId: '1:857113063928:web:9ad9a014b4ea4dc971260d',
    messagingSenderId: '857113063928',
    projectId: 'gestao-facil-9565c',
    authDomain: 'gestao-facil-9565c.firebaseapp.com',
    storageBucket: 'gestao-facil-9565c.firebasestorage.app',
    measurementId: 'G-QFF79VW84V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4WxArx20FPpVPvb_Mi-J57bPXO5jmVp4',
    appId: '1:857113063928:android:0b9132552ba475ed71260d',
    messagingSenderId: '857113063928',
    projectId: 'gestao-facil-9565c',
    storageBucket: 'gestao-facil-9565c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-T6ZAW5JRY6Sj5J9eRR4Oy8BNzRaWFQ',
    appId: '1:857113063928:ios:e63166aaa19ecbeb71260d',
    messagingSenderId: '857113063928',
    projectId: 'gestao-facil-9565c',
    storageBucket: 'gestao-facil-9565c.firebasestorage.app',
    iosBundleId: 'com.example.gestaoFacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE-T6ZAW5JRY6Sj5J9eRR4Oy8BNzRaWFQ',
    appId: '1:857113063928:ios:e63166aaa19ecbeb71260d',
    messagingSenderId: '857113063928',
    projectId: 'gestao-facil-9565c',
    storageBucket: 'gestao-facil-9565c.firebasestorage.app',
    iosBundleId: 'com.example.gestaoFacil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuLjfqQRS662xKaPec_iFkRMXGNeY-Ma8',
    appId: '1:857113063928:web:ea15637ddd2f30e171260d',
    messagingSenderId: '857113063928',
    projectId: 'gestao-facil-9565c',
    authDomain: 'gestao-facil-9565c.firebaseapp.com',
    storageBucket: 'gestao-facil-9565c.firebasestorage.app',
    measurementId: 'G-0W82Y4PFCC',
  );
}
